/*=========================CONCEPTION DES PROCEDURE STOCKEES==============================*/
DELIMITER//
CREATE PROCEDURE GESTION_UNITE(
	IN U_OPERATION TEXT,
	IN U_CODEUNITE INT,
	IN U_DESIGNATION TEXT,
	IN U_SIGNE TEXT,
	IN U_AUTEUR TEXT
)
BEGIN
	DECLARE
		CODE   INT;
 -- Condition IF pour l'OPERATION
		IF     U_OPERATION = 'INSERT' THEN
			SET CODE=(
				SELECT
					COALESCE(MAX(CODEUNITE),
					0)+1
				FROM
					UNITE
			);
			INSERT IGNORE INTO UNITE (CODEUNITE, DESIGNATION, SIGLE, AUTEUR) VALUES (CODE, U_DESIGNATION, U_SIGLE, U_AUTEUR);
			ELSEIF U_OPERATION = 'UPDATE' THEN
				UPDATE UNITE SET DESIGNATION = U_DESIGNATION, SIGLE = U_SIGLE, AUTEUR=U_AUTEUR WHERE CODEUNITE = U_CODEUNITE;
				ELSEIF U_OPERATION = 'DELETE' THEN
					DELETE * FROM UNITE WHERE CODEUNITE = U_CODEUNITE;
					ELSEIF U_OPERATION = 'SELECT' THEN
						SELECT
							*
						FROM
							UNITE
						WHERE
							CODEUNITE = U_CODEUNITE;
						ELSE  
 -- Gérer d'autres actions ou afficher un message d'erreur
						SELECT
							'Action non reconnue' AS MESSAGE;
					END IF;
				END // DELIMITER;